//Compteurs
export const ADD_COMPTEUR_COMMANDE = "ADD_COMPTEUR_COMMANDE"
export const ADD_COMPTEUR_FACTURE = "ADD_COMPTEUR_FACTURE"
export const ADD_COMPTEUR_RETOUR = "ADD_COMPTEUR_RETOUR"
export const INIT_COMPTEURS = "INIT_COMPTEURS"

// Users
export const ADD_USER = "ADD_USER"
export const REMOVE_USER = "REMOVE_USER"

//Parametres
export const ADD_PARAMETRE = "ADD_PARAMETRE"
export const REMOVE_PARAMETRE = "REMOVE_PARAMETRE"

//ArticlesMembre
export const ADD_ARTICLE_MEMBRE = "ADD_ARTICLE_MEMBRE"
export const REMOVE_ARTICLE_MEMBRE = "REMOVE_ARTICLE_MEMBRE"
export const REMOVE_ALL_ARTICLE_MEMBRE = "REMOVE_ALL_ARTICLE_MEMBRE"

//BonsMembre
export const ADD_BON_MEMBRE = "ADD_BON_MEMBRE"
export const REMOVE_BON_MEMBRE = "REMOVE_BON_MEMBRE"
export const REMOVE_ALL_BON_MEMBRE = "REMOVE_ALL_BON_MEMBRE"

//ArticlesStandby
export const LOAD_ARTICLE_STANDBY = "LOAD_ARTICLE_STANDBY"
export const DELETE_ARTICLE_STANDBY = "DELETE_ARTICLE_STANDBY"
export const COMANDABLE_ARTICLE_STANDBY = "COMANDABLE_ARTICLE_STANDBY"
export const CHANGE_CLUB_ARTICLE_STANDBY = "CHANGE_CLUB_ARTICLE_STANDBY"
export const REMOVE_ARTICLE_STANDBY = "REMOVE_ARTICLE_STANDBY"

//BonsStandby
export const LOAD_BON_STANDBY = "LOAD_BON_STANDBY"
export const DELETE_BON_STANDBY = "DELETE_BON_STANDBY"
export const COMANDABLE_BON_STANDBY = "COMANDABLE_BON_STANDBY"
export const REMOVE_BON_STANDBY = "REMOVE_BON_STANDBY"

//Commandes
export const LOAD_COMMANDE = "LOAD_COMMANDE"
export const ADD_COMMANDE = "ADD_COMMANDE"
export const ADD_ARTICLE_COMMANDE = "ADD_ARTICLE_COMMANDE"
export const ADD_BON_COMMANDE = "ADD_BON_COMMANDE"
export const REMOVE_COMMANDE = "REMOVE_COMMANDE"

