//Compteurs
export const ADD_COMPTEUR_COMMANDE = "ADD_COMPTEUR_COMMANDE"
export const ADD_COMPTEUR_FACTURE = "ADD_COMPTEUR_FACTURE"
export const ADD_COMPTEUR_RETOUR = "ADD_COMPTEUR_RETOUR"
export const INIT_COMPTEURS = "INIT_COMPTEURS"

// Users
export const ADD_USER = "ADD_USER"
export const UPDATE_USER = "UPDATE_USER"
export const REMOVE_USER = "REMOVE_USER"

//Parametres
export const ADD_PARAMETRE = "ADD_PARAMETRE"
export const REMOVE_PARAMETRE = "REMOVE_PARAMETRE"

//ArticlesMembre
export const ADD_ARTICLE_MEMBRE = "ADD_ARTICLE_MEMBRE"
export const REMOVE_ARTICLE_MEMBRE = "REMOVE_ARTICLE_MEMBRE"
export const REMOVE_ALL_ARTICLE_MEMBRE = "REMOVE_ALL_ARTICLE_MEMBRE"

//BonsMembre
export const ADD_BON_MEMBRE = "ADD_BON_MEMBRE"
export const REMOVE_BON_MEMBRE = "REMOVE_BON_MEMBRE"
export const REMOVE_ALL_BON_MEMBRE = "REMOVE_ALL_BON_MEMBRE"

//ArticlesStandby
export const LOAD_ARTICLE_STANDBY = "LOAD_ARTICLE_STANDBY"
export const DELETE_ARTICLE_STANDBY = "DELETE_ARTICLE_STANDBY"
export const COMANDABLE_ARTICLE_STANDBY = "COMANDABLE_ARTICLE_STANDBY"
export const CHANGE_CLUB_ARTICLE_STANDBY = "CHANGE_CLUB_ARTICLE_STANDBY"
export const REMOVE_ARTICLE_STANDBY = "REMOVE_ARTICLE_STANDBY"

//BonsStandby
export const LOAD_BON_STANDBY = "LOAD_BON_STANDBY"
export const DELETE_BON_STANDBY = "DELETE_BON_STANDBY"
export const COMANDABLE_BON_STANDBY = "COMANDABLE_BON_STANDBY"
export const REMOVE_BON_STANDBY = "REMOVE_BON_STANDBY"

//Commandes
export const LOAD_COMMANDE = "LOAD_COMMANDE"
export const ADD_COMMANDE = "ADD_COMMANDE"
export const ADD_ARTICLE_COMMANDE = "ADD_ARTICLE_COMMANDE"
export const ADD_BON_COMMANDE = "ADD_BON_COMMANDE"
export const REMOVE_COMMANDE = "REMOVE_COMMANDE"
export const REMOVE_ALL_COMMANDE = "REMOVE_ALL_COMMANDE"

//PrepaFactures
export const ADD_PREPA_FACTURE = "ADD_PREPA_FACTURE"
export const ADD_ARTICLE_PREPA_FACTURE = "ADD_ARTICLE_PREPA_FACTURE"
export const ADD_BON_PREPA_FACTURE = "ADD_BON_PREPA_FACTURE"
export const REMOVE_PREPA_FACTURE = "REMOVE_PREPA_FACTURE"
export const REMOVE_ALL_PREPA_FACTURE = "REMOVE_ALL_PREPA_FACTURE"

//PrepaFactDepot
export const ADD_PREPA_FACT_DEPOT = "ADD_PREPA_FACT_DEPOT"
export const ADD_ARTICLE_PREPA_FACT_DEPOT = "ADD_ARTICLE_PREPA_FACT_DEPOT"
export const REMOVE_BON_PREPA_FACT_DEPOT = "REMOVE_BON_PREPA_FACT_DEPOT"
export const ADD_BON_PREPA_FACT_DEPOT = "ADD_BON_PREPA_FACT_DEPOT"
export const REMOVE_PREPA_FACT_DEPOT = "REMOVE_PREPA_FACT_DEPOT"
export const REMOVE_ALL_PREPA_FACT_DEPOT = "REMOVE_ALL_PREPA_FACT_DEPOT"

//Factures
export const LOAD_FACTURE = "LOAD_FACTURE"
export const ADD_FACTURE = "ADD_FACTURE"
export const ADD_ARTICLE_FACTURE = "ADD_ARTICLE_FACTURE"
export const ADD_BON_FACTURE = "ADD_BON_FACTURE"
export const REGLER_FACTURE = "REGLER_FACTURE"
export const REMOVE_FACTURE = "REMOVE_FACTURE"
export const REMOVE_ALL_FACTURE = "REMOVE_ALL_FACTURE"

//Depot
export const LOAD_DEPOT = "LOAD_DEPOT"
export const ADD_ARTICLE_DEPOT = "ADD_ARTICLE_DEPOT"
export const FACTURABLE_ARTICLE_DEPOT = "FACTURABLE_ARTICLE_DEPOT"
export const RETOURNABLE_ARTICLE_DEPOT = "RETOURNABLE_ARTICLE_DEPOT"
export const REMOVE_ARTICLE_DEPOT = "REMOVE_ARTICLE_DEPOT"
export const REMOVE_ALL_DEPOT = "REMOVE_ALL_DEPOT"


//BonsDepot
export const LOAD_BON_DEPOT = "LOAD_BON_DEPOT"
export const ADD_BON_DEPOT = "ADD_BON_DEPOT"
export const FACTURABLE_BON_DEPOT = "FACTURABLE_BON_DEPOT"
export const REMOVE_BON_DEPOT= "REMOVE_BON_DEPOT"
export const REMOVE_ALL_BON_DEPOT = "REMOVE_ALL_BON_DEPOT"


//Retours
export const LOAD_RETOUR = "LOAD_RETOUR"
export const ADD_RETOUR = "ADD_RETOUR"
export const ADD_ARTICLE_RETOUR = "ADD_ARTICLE_RETOUR"
export const RETOURNER_RETOUR = "RETOURNER_RETOUR"
export const REMOVE_RETOUR = "REMOVE_RETOUR"
export const REMOVE_ALL_RETOUR = "REMOVE_ALL_RETOUR"


//Gestion utilisateurs
export const LOAD_USERS = "LOAD_USERS"
export const ADD_USERS = "ADD_USERS"
export const UPDATE_ROLE_USERS = "UPDATE_ROLE_USERS"
export const DELETE_USERS = "DELETE_USERS"
export const REMOVE_ALL_USERS = "REMOVE_ALL_USERS"